# Generated by Django 5.0.6 on 2024-09-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoproducto',
            options={'verbose_name_plural': 'Estados de Producto'},
        ),
        migrations.AlterModelTable(
            name='estadoproducto',
            table='store_estado_producto',
        ),
    ]
