# Generated by Django 5.0.6 on 2024-07-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='dv',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='region',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rut',
        ),
    ]
