# Generated by Django 5.0.6 on 2024-07-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_remove_usuario_comuna_remove_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categoria'),
        ),
    ]
