# Generated by Django 5.0.6 on 2024-09-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_alter_estadoproducto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estadoProducto',
        ),
        migrations.DeleteModel(
            name='estadoProducto',
        ),
    ]
