# Generated by Django 5.0.6 on 2024-07-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_categoria_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='imagen',
            new_name='imagenCat',
        ),
    ]
