# Generated by Django 5.0.6 on 2024-09-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_producto_estadoproducto_delete_estadoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='en_carrusel',
            field=models.BooleanField(default=False, verbose_name='Mostrar en el carrusel'),
        ),
    ]
