# Generated by Django 5.0.6 on 2024-07-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_rename_imagen_categoria_imagencat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='STORE_CATEGORIA',
        ),
    ]
