# Generated by Django 5.0.6 on 2024-09-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_categoria_en_carrusel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='en_carrusel',
        ),
        migrations.AddField(
            model_name='categoria',
            name='visible_en_carrusel',
            field=models.BooleanField(default=False, verbose_name='Visible en carrusel'),
        ),
    ]
