# Generated by Django 5.0.6 on 2024-09-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_venta_cantidad_venta_precio_unitario_venta_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
