# Generated by Django 5.0.6 on 2024-09-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
