# Generated by Django 5.0.6 on 2024-09-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_sitesettings_delete_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteSettings',
            new_name='Logo',
        ),
    ]
