# Generated by Django 5.0.6 on 2024-09-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_venta_imagen_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
    ]
