# Generated by Django 5.0.6 on 2024-09-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_rename_sitesettings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
            ],
        ),
    ]
