# Generated by Django 5.0.6 on 2024-09-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_producto_destacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuienesSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido')),
            ],
            options={
                'db_table': 'quienes_somos',
            },
        ),
    ]
